# The west manifest file for upstream Zephyr.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom Zephyr installations.
# For example, you could create a manifest file in your own out of
# tree application directory, which would pull this zephyr repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.

manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos
    - name: recogni
      url-base: git@github.com:recogni

  #
  # Please add items below based on alphabetical order
  projects:
    - name: fatfs
      path: modules/fs/fatfs
    - name: littlefs
#      revision: 6372f515fe59616bd7e00ca7bcce762c05ab029b
      revision: 9e4498d1c73009acd84bb36036ee5e2869112a6c
      path: modules/fs/littlefs
    - name: mbedtls
      revision: 53044168b43f06ec5654b906a2cdd260bf477edd
      path: modules/crypto/mbedtls

  self:
    path: zephyr
    west-commands: scripts/west-commands.yml

